spring.application.name=Simple Calculator

server.port=8080

server.servlet.context-path=/calc

logging.level.root=INFO
logging.level.com.example.calculator=DEBUG

spring.http.encoding.charset=UTF-8
spring.http.encoding.enable=true
